menu:
  首页: /
  归档: /archives
  关于: /aboutme
  工具: /tools
  

widgets:
- search ##swiftype
- category
- twitter
- tagcloud
- archive
- weibo


excerpt_link: 阅读全文

#plugins:



twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

#google_analytics: UA-41207871-1
rss: http://giscafer.com/atom.xml

# swiftype
swift_search:
  enable: true

